---
# https://www.linuxtechi.com/setup-bind-server-centos-8-rhel-8/
- name: Install DNS
  become: true
  tags: install
  block:
    - name: Install needed packages
      dnf:
        name:
          - bind
          - bind-utils
        state: latest

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: internal
        state: enabled
        permanent: yes
        immediate: yes
        service: dns

    - name: Download root.hints
      get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/named/named.ca
        owner: root
        group: named
        mode: '0640'

# https://ftp.eenet.ee/pub/isc/dnssec-guide/html/dnssec-guide.html#validation-easy-start-explained
    - name: Replace root key with our own
      copy:
        content: 'trusted-keys {. 257 3 8 "AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU=";};'
        dest: /etc/named.root.key
        owner: root
        group: named
        mode: '0644'

    - name: Write out named file
      template:
        src: named.conf.j2
        dest: /etc/named.conf
        owner: root
        group: named
        mode: '0640'

    - name: Write out "{{ baseName }}.{{ baseDomain }}" zone file
      template:
        src: zonefile.j2
        dest: /var/named/named.lab.local.forward
        owner: root
        group: named
        mode: '0640'

    - name: Write out reverse zone file
      template:
        src: reverse.j2
        dest: /var/named/named.lab.local.reverse
        owner: root
        group: named
        mode: '0640'

    - name: Write out auto.local zone file
      template:
        src: named.auto.local.forward.j2
        dest: /var/named/named.auto.local.forward
        owner: root
        group: named
        mode: '0640'

    - name: Copy over file for blackhole of ads
      copy:
        src: /var/named/named.empty
        dest: /var/named/null.zone.file
        remote_src: yes
        owner: root
        group: named
        mode: '0640'

    - name: Copy over add blocking list
      uri:
        url: "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=bindconfig&showintro=0&mimetype=plaintext"
        follow_redirects: all
        dest: /etc/named.adblock
        owner: root
        group: named
        mode: '0640'

    - name: Set the local resolv.conf file
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Starting services
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - named