---

- name: Install HTTP server
  become: true
  tags: install
  block:
    - name: Install needed packages
      dnf:
        name:
          - httpd
        state: latest

    - name: Configure Firewalld
      ignore_errors: yes
      firewalld:
        zone: internal
        state: enabled
        permanent: yes
        immediate: yes
        port: 8080/tcp

    - name: Ensure the default Apache port is 8080
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080

    - name: SELinux role to allow HAProxy to access ports 8080
      include_role:
        name: rhel-system-roles.selinux

    - name: Starting services
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - httpd
